#
# Copyright (c) 2020 Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
#
# Author: OIG Development
#
# Description: docker compose yaml to run OIG with external DB
#
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
#
#
version: "3.0"

services:
  #
  # The OIG Admin Server
  #
  oimadmin:
    image: ${OIG_IMAGE}
    container_name: oimadmin
    hostname: oimadmin
    command: /bin/bash -c "sleep 5s; /u01/oracle/dockertools/createDomainAndStart.sh"
    ports:
      - "7001:7001"
    environment:
      - ADMIN_HOST=${DC_HOSTNAME}
      - ADMIN_PASSWORD=${DC_ADMIN_PWD}
      - CONNECTION_STRING=${DC_ORCL_HOST}:${DC_ORCL_PORT}:${DC_ORCL_SID}
      - DB_PASSWORD=${DC_ORCL_SYSPWD}
      - DB_SCHEMA_PASSWORD=${DC_RCU_SCHPWD}
      - RCUPREFIX=${DC_RCU_OIMPFX}
    healthcheck:
      test: ["CMD", "curl", "-fL", "http://oimadmin:7001/console"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    volumes:
      - ${DC_DDIR_OIM}:/u01/oracle/user_projects

  #
  # The SOA Managed Server
  #
  soams:
    image: ${OIG_IMAGE}
    container_name: soams
    hostname: soams
    depends_on:
      - "oimadmin"
    command: /bin/bash -c "/u01/oracle/dockertools/startMS.sh"
    ports:
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
    environment:
      - ADMIN_HOST=${DC_HOSTNAME}
      - ADMIN_PORT=7001
      - ADMIN_PASSWORD=${DC_ADMIN_PWD}
      - MANAGED_SERVER=soa_server1
      - MS_HOST=${DC_HOSTNAME}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://soams:8001/soa-infra"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    volumes:
      - ${DC_DDIR_OIM}:/u01/oracle/user_projects

  #
  # The OIG Managed Server
  #
  oimms:
    image: ${OIG_IMAGE}
    container_name: oimms
    hostname: oimms
    depends_on:
      - "oimadmin"
    command: /bin/bash -c "/u01/oracle/dockertools/startMS.sh"
    ports:
      - "14000:14000"
      - "14001:14001"
      - "14002:14002"
    environment:
      - ADMIN_HOST=${DC_HOSTNAME}
      - ADMIN_PORT=7001
      - ADMIN_PASSWORD=${DC_ADMIN_PWD}
      - MANAGED_SERVER=oim_server1
      - MS_HOST=${DC_HOSTNAME}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://oimms:14000/identity"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    volumes:
      - ${DC_DDIR_OIM}:/u01/oracle/user_projects

